### ISSUE TITLE
Add a box to select/unselect all

### ISSUE THREAD

**Issue by licharlot** [andrsd/mesh-inspector#54]
- blocks
- side sets
- node sets

**Comment by andrsd** [comment]
When you select all of {blocks | side sets | node set}, do you just want to see them or are you also looking for the total number of {elements | nodes} in the info area at the top left?

And I am assuming you maybe want this for the case where you have a lot of blocks and you want to select all of them and then unselect a few?

**Comment by licharlot** [comment]
I don't have a use case at the moment for seeing the total number of {elements | nodes}, but that can be useful. 

> 

> 

> And I am assuming you maybe want this for the case where you have a lot of blocks and you want to select all of them and then unselect a few?

Exactly 🙂 . Or unselect all and select a few

**Comment by andrsd** [comment]
So I looked into this and originally, I thought I would add a checkbox right next to the *Name* in the widget header (like we are used to from paraview). However, that opened a can of worms in Qt, where that is not really possible and code needs to be written. I did write the code, but it created all sorts of other issues *sigh*.

So, I am thinking about changing the GUI like this:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/85632/196050782-b61df5e1-2837-4a44-a763-158c56db7383.png">

So, clicking the checkbox in front of the Block | Side set | Node set would select/deselect all its childs. Those items can be expanded/collapsed like we are able to do currently.

Also, I noticed that I implemented a context menu for blocks where you can hide/show all, and more. But, this is not implemented for side/node sets.  That made me think if context menus are no longer a thing and people expect to see all possible functionality from what is presented on the screen (like we are trained from smartphones - we don't really tap and hold anymore). Then, the interface above would be probably an improvement.

Comments/thoughts?

**Comment by licharlot** [comment]
Yes that interface would be great!
